version: "3.8"
services: 
    ubuntu:
        build: 
            context: ./
            dockerfile: Dockerfile
        env_file: .env   
        environment:
            - AWS_DEFAULT_REGION=ap-southeast-2
        working_dir: /src
        volumes:
            - .:/src 
