version: "3.3"

services:
  devops-toolbox:
    image: alanrlima/devops-toolbox:full
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${HOME}/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - TF_IN_AUTOMATION=yes